name: restaurant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.3.0
  sqflite: ^2.4.1
  shared_preferences: ^2.5.1
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  test: ^1.25.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100

flutter_native_splash:
  color: "#FFF8F5" # Background color for the splash screen
  color_dark: "#000000"   # Background color for dark mode
  image: assets/icons/splash_icon.png # Path to your splash icon
  android: true # Enable splash screen for Android
  ios: true # Enable splash screen for iOS
  web: false # Disable splash screen for web
  android_gravity: center # Position of the splash icon
  ios_content_mode: scaleAspectFit # iOS content mode

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png" # Path to your app icon image
  min_sdk_android: 21 # Optional: Set min SDK version
